### ISSUE TITLE
Leaks memory until killed by kernel

### ISSUE THREAD

**Issue by dankempster** [ergonode/docker#67]
## Bug type
Other

## Current behavior
Running the Ergonode frontend and backend skeletons in a docker environment based on `ergonode/docker`, the `nuxtjs` container is killed after consuming all the memory allocated to Docker (for Mac).

The `nuxtjs` container successfully compiles the app and starts listening, you can even use the app for a few minutes before it stops responding. Inspecting docker logs reveals

```
nuxtjs_1                      | ℹ Waiting for file changes
nuxtjs_1                      | ℹ Memory usage: 1.16 GB (RSS: 2.11 GB)
nuxtjs_1                      | ℹ Listening on: http://192.168.16.4:80/
ergonode-docker_nuxtjs_1 exited with code 0
```

Starting the container and monitoring it's resource usage with `docker stats` shows it continues to consume memory until it's killed by Docker. -- Very annoyingly, Docker logs this the same as if the process just quit itself with exit code zero.

I only noticed this after upgrading my app to beta8. Unfortunately, due to the changes made between beta7 & 8, I've been unable to revert to beta7 to see if the problem persists there.

This is only an issue with this `ergononode/skeleton-frontend` repository. Verified by running the `ergonode/frontend` code in the same environment and it doesn't leak memory.

## Input Code
To minimise the chance of anything in my code being the culprit, we'll use Ergonode repositories or forks of:

### With `make`
For your convenience, I've created `skeleton-frontend/expose-memory-leak-issue` branch in my [`dankempster/ergonode-docker`](https://github.com/dankempster/ergonode-docker) repository. This branch has a copy of the Makefile I use with additional targets for testing this issue, all other code is Ergonode's own.

Please clone my branch and run `make useskeleton`. This will set up the full Ergonode environment.

Once the build is finished, `docker stats` will run to allow you to monitor the nuxtjs container's memory usage.
Run `make nuxtjslogs` in second terminal to monitor it's log output.

### Without `make`
Clone `ergonode/docker` to your machine. Follow your standard process for setting it up, except for where it concerns the `frontend/`. For the frontend clone the skeleton repo:

```bash
git clone --branch 'v1.0.0-beta.8' -- git@github.com:ergonode/skeleton-frontend.git frontend
```

While ergonode/skeleton-frontend#10 is unresolved you'll need to checkout the beta8 merge commit directly:
```bash
git --git-dir=frontend/.git --work-tree=frontend/ checkout b0472c9b0baf3b738f8900f1bd361e1e2f33a890
```

Now build and start the environment

```bash
docker-compose up -d
```

Once the build is complete, monitor the `nuxtjs` container

```bash
docker stats

# in a second terminal
docker-compose logs -f nuxtjs
```

### Expedite replication
The exact timeframe it takes to be killed will depend on how much memory your machine has. To expedite the replication I suggest reducing the amount of memory allocated to Docker, if you can.

## Expected behavior
The container running the app to not consume all the memory and run indefinitely.

## Possible Solution
Not a clue, sorry.

## Environment

<pre><code>
Ergonode version: v1.0.0 beta 8, commit b0472c9b0baf3b738f8900f1bd361e1e2f33a890
 
Detailed information:
- Node version: 12.6
- Browser (Version): N/A
- Platform:  Container=alpine-linux, host=Mac-10.15.7

Others:
 - Docker for Mac v2.5.0.1
</code></pre>

**Comment by bleto** [comment]
Hi @dankempster , thanks for reporting :) 
We are verifying the problem. 

P.S. I have moved your ticket to the `docker' repository. the [skeleton](https://github.com/ergonode/skeleton) and [skeleton-frontend](https://github.com/ergonode/skeleton-frontend) repositories we disable the ability to report issues to keep things tidy. We will accept reports on our main development repositories.

**Comment by Daniel-Marynicz** [comment]
When i removed directory node_modules and changed in the Dockerfile  "FROM node:12.6-alpine as node"  to  "FROM node:14.15-alpine as node"
And rebuild this with `docker-compose build`. 
Then this problem was solved.

**Comment by dankempster** [comment]
I can confirm that after upgrading to Node 14.15, I no longer experience this issue.

**Comment by damianbobrowski** [comment]
I met problem yesterday. Upgrading node as described above helps me with memory leak too.
