### ISSUE TITLE
docker-compose.yml (Development): Fixture not loaded

### ISSUE THREAD

**Issue by jjarolim** [ergonode/docker#68]
Hi!

FYI: After starting the default docker container, we could not sign in as Johnny Bravo: Always got an "Invalid credentials" error.

Running `$ php bin/console ergonode:fixture:load` in the php container fixed the problem - seems something went wrong during the startup/bootstrapping.

Best from Salzburg, Austria!

**Comment by piotrkreft** [comment]
Hi, @jjarolim, as described in [README.md](https://github.com/ergonode/docker/blob/develop/README.md#database-filling) - this step, is to be performed manually. Otherwise, you'd have a fresh database on each container creation and therefore no persistent data. Hope it's clear
