### ISSUE TITLE
curl: (7) Failed to connect to rabbitmq port 15672: Connection refused

### ISSUE THREAD

**Issue by nidhaldring** [ergonode/docker#76]
I have followed the docs about how to install ergonode with docker and configured my .env.local file like this

`MESSENGER_TRANSPORT_DSN=amqp://ergonode:ergonode@rabbitmq:5672/%2f/messages
MAILER_DSN=smtp://mailhog:1025
`
yet i always get this error for all php related services
`php-messenger-segment_1       | Linking /usr/local/etc/php/php.ini-development > /usr/local/etc/php/php.ini
php-messenger-segment_1       | Verified OK
php-messenger-segment_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
php-messenger-segment_1       |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
php-messenger-segment_1       | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-segment_1       | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-segment_1       | Linking /usr/local/etc/php/php.ini-development > /usr/local/etc/php/php.ini
php-messenger-segment_1       | Verified OK
php-messenger-segment_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
php-messenger-segment_1       |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
php-messenger-segment_1       | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-segment_1       | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-segment_1       | Linking /usr/local/etc/php/php.ini-development > /usr/local/etc/php/php.ini
php-messenger-segment_1       | Verified OK
php-messenger-segment_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
php-messenger-segment_1       |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
php-messenger-segment_1       | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-segment_1       | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-completeness_1  | Verified OK
php-messenger-completeness_1  | Verified OK
php-messenger-notification_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
php-messenger-notification_1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
php-messenger-notification_1  | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-notification_1  | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
ergonode_php-messenger-notification_1 exited with code 7
php-messenger-batch_action_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
php-messenger-batch_action_1  |                                  Dload  Upload   Total   Spent    Left  Speed
php-messenger-import_1        |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
php-messenger-import_1        |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
php-messenger-batch_action_1  | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-batch_action_1  | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
php-messenger-import_1        | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
php-messenger-import_1        | curl: (7) Failed to connect to rabbitmq port 15672: Connection refused
ergonode_php-messenger-batch_action_1 exited with code 7
ergonode_php-messenger-import_1 exited with code 7
`

**Comment by offgrid88** [comment]
Same isssue here
