### ISSUE TITLE
Running the default installation instructions results in error 'pull access denied for ergonode/php'

### ISSUE THREAD

**Issue by lennartvdd** [ergonode/docker#85]
Running docker-compose up with the default installation instructions results in error 'pull access denied for ergonode/php'

![image](https://user-images.githubusercontent.com/1104561/147114958-33e7524a-ad56-4b96-ae89-fcde6d434fcf.png)

Succesfully authenticated using `docker login`
Followed the procedure in the README.md using all defaults in env.dist

**Comment by cubu** [comment]
I have the same issue. Tried multiple OS, still the same result.

**Comment by villejuutila** [comment]
Having the same issue here. Anything new?

**Comment by piotrkreft** [comment]
@lennartvdd @cubu  sorry but the repository is obsolete. Ergonode stopped maintaining over a year ago and as of now, we are not planning to continue to work with that Open Source code.
If you'd like to see Ergonode in action please go ahead and book a demo to see all its power https://www.ergonode.com/book-a-demo
