### ISSUE TITLE
Docker compose up fail (required packages and PHP extensions)

### ISSUE THREAD

**Issue by pvogler-loesch** [ergonode/docker#88]
Below is the error while docker compose up run:
------
#0 80.56 
#0 80.56 Build process completed successfully
#0 80.56 Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20190902/amqp.so'
#0 80.58 install ok: channel://pecl.php.net/amqp-1.11.0
#0 80.58 configuration option "php_ini" is not set to php.ini location
#0 80.58 You should add "extension=amqp.so" to php.ini
#0 80.59 + pecl install xdebug
#0 82.55 pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.4.33
#0 82.55 No valid packages found
#0 82.55 install failed
------
failed to solve: executor failed running [/bin/sh -c set -eux ;     apk add  --no-cache git          zip         unzip         curl         rabbitmq-c         libpq         icu-libs         graphviz         acl         fcgi          bash         libcurl         gettext         gnu-libiconv         libpng         libjpeg         freetype         libwebp         imagemagick         libxpm         libzip          busybox-suid ;     apk add --no-cache --virtual .fetch-deps         icu-dev         postgresql-dev         rabbitmq-c-dev         autoconf         musl-dev         gcc         g++         make         pkgconf         file         curl-dev         libpng-dev         jpeg-dev         freetype-dev         libwebp-dev         libzip-dev         imagemagick-dev         libxpm-dev ;     docker-php-ext-configure gd       --with-webp     --with-jpeg     --with-xpm     --with-freetype ;     docker-php-ext-install -j$(nproc)     pdo      pdo_pgsql     intl     pcntl      gd     exif      zip      opcache ;     pecl install amqp ;     pecl install xdebug;     pecl install imagick ;     docker-php-ext-enable amqp ;     docker-php-ext-enable xdebug ;     docker-php-ext-enable imagick ;     mkdir -p /tmp/newrelic ;     cd /tmp/newrelic ;     curl -L "${NEWRELIC_URL}" -o newrelic.tar.gz ;      sha256sum newrelic.tar.gz  | grep "${NEWRELIC_SHA256SUM}" ;     tar -xf newrelic.tar.gz ;     NR_INSTALL_USE_CP_NOT_LN=1  NR_INSTALL_SILENT=1 ./newrelic-php5-*/newrelic-install install ;     rm -rf /tmp/newrelic ;     php --version ;     rm -rf /tmp/* ;     update-ca-certificates]: exit code: 1
(base) p.vogler@MacBook-Vogler ergonode % ./run_tests #

**Comment by piotrkreft** [comment]
@pvogler-loesch  sorry but the repository is obsolete. Ergonode stopped maintaining over a year ago and as of now, we are not planning to continue to work with that Open Source code.
If you'd like to see Ergonode in action please go ahead and book a demo to see all its power https://www.ergonode.com/book-a-demo
