### ISSUE TITLE
Docker install failed importing cache manifest

### ISSUE THREAD

**Issue by StevenSermeus** [ergonode/docker#89]
Docker version: 23.0.0
Docker compose : 2.15.1
OS : Ubuntu 20.04

I followed install guide but at the first docker-compose up i got some errors.

php-messenger-import Error 
php-messenger-export Error 
php-messenger-completeness Error
php-messenger-completeness Error
ERROR [ergonode/php:latest] importing cache manifest from ergonode/haproxy:latest
ERROR [ergonode/nuxtjs:latest] importing cache manifest from ergonode/php:latest
ERROR [ergonode/nuxtjs:latest] importing cache manifest from ergonode/nuxtjs:latest
ERROR [ergonode/nuxtjs:latest] importing cache manifest from ergonode/docsify:latest 
ERROR [ergonode/nuxtjs:latest] importing cache manifest from ergonode/nginx:latest

`failed to solve: executor failed running [/bin/sh -c set -eux ;     apk add  --no-cache git          zip         unzip         curl         rabbitmq-c         libpq         icu-libs         graphviz         acl         fcgi          bash         libcurl         gettext         gnu-libiconv         libpng         libjpeg         freetype         libwebp         imagemagick         libxpm         libzip          busybox-suid ;     apk add --no-cache --virtual .fetch-deps         icu-dev         postgresql-dev         rabbitmq-c-dev         autoconf         musl-dev         gcc         g++         make         pkgconf         file         curl-dev         libpng-dev         jpeg-dev         freetype-dev         libwebp-dev         libzip-dev         imagemagick-dev         libxpm-dev ;     docker-php-ext-configure gd       --with-webp     --with-jpeg     --with-xpm     --with-freetype ;     docker-php-ext-install -j$(nproc)     pdo      pdo_pgsql     intl     pcntl      gd     exif      zip      opcache ;     pecl install amqp ;     pecl install xdebug;     pecl install imagick ;     docker-php-ext-enable amqp ;     docker-php-ext-enable xdebug ;     docker-php-ext-enable imagick ;     mkdir -p /tmp/newrelic ;     cd /tmp/newrelic ;     curl -L "${NEWRELIC_URL}" -o newrelic.tar.gz ;      sha256sum newrelic.tar.gz  | grep "${NEWRELIC_SHA256SUM}" ;     tar -xf newrelic.tar.gz ;     NR_INSTALL_USE_CP_NOT_LN=1  NR_INSTALL_SILENT=1 ./newrelic-php5-*/newrelic-install install ;     rm -rf /tmp/newrelic ;     php --version ;     rm -rf /tmp/* ;     update-ca-certificates]: exit code: `

Maybe it's a me error but don't know what error i made :) 

All help is welcome :+1:

**Comment by piotrkreft** [comment]
@StevenSermeus sorry but the repository is obsolete. Ergonode stopped maintaining over a year ago and as of now, we are not planning to continue to work with that Open Source code.
If you'd like to see Ergonode in action please go ahead and book a demo to see all its power https://www.ergonode.com/book-a-demo
